
package es.gob.oaw.sim;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnvioMensajesService", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/", wsdlLocation = "https://misim.redsara.es/misim-bus-webapp/EnvioMensajesService?wsdl")
public class EnvioMensajesService
    extends Service
{

    /** The Constant ENVIOMENSAJESSERVICE_WSDL_LOCATION. */
    private static final URL ENVIOMENSAJESSERVICE_WSDL_LOCATION;
    
    /** The Constant ENVIOMENSAJESSERVICE_EXCEPTION. */
    private static final WebServiceException ENVIOMENSAJESSERVICE_EXCEPTION;
    
    /** The Constant ENVIOMENSAJESSERVICE_QNAME. */
    private static final QName ENVIOMENSAJESSERVICE_QNAME = new QName("http://misim.redsara.es/misim-bus-webapp/", "EnvioMensajesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://pre-misim.redsara.es/misim-bus-webapp/EnvioMensajesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENVIOMENSAJESSERVICE_WSDL_LOCATION = url;
        ENVIOMENSAJESSERVICE_EXCEPTION = e;
    }

    /**
	 * Instantiates a new envio mensajes service.
	 */
    public EnvioMensajesService() {
        super(internalGetWsdlLocation(), ENVIOMENSAJESSERVICE_QNAME);
    }

    /**
	 * Instantiates a new envio mensajes service.
	 *
	 * @param features the features
	 */
    public EnvioMensajesService(WebServiceFeature... features) {
        super(internalGetWsdlLocation(), ENVIOMENSAJESSERVICE_QNAME, features);
    }

    /**
	 * Instantiates a new envio mensajes service.
	 *
	 * @param wsdlLocation the wsdl location
	 */
    public EnvioMensajesService(URL wsdlLocation) {
        super(wsdlLocation, ENVIOMENSAJESSERVICE_QNAME);
    }

    /**
	 * Instantiates a new envio mensajes service.
	 *
	 * @param wsdlLocation the wsdl location
	 * @param features     the features
	 */
    public EnvioMensajesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENVIOMENSAJESSERVICE_QNAME, features);
    }

    /**
	 * Instantiates a new envio mensajes service.
	 *
	 * @param wsdlLocation the wsdl location
	 * @param serviceName  the service name
	 */
    public EnvioMensajesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
	 * Instantiates a new envio mensajes service.
	 *
	 * @param wsdlLocation the wsdl location
	 * @param serviceName  the service name
	 * @param features     the features
	 */
    public EnvioMensajesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
	 * Gets the envio mensajes service port.
	 *
	 * @return returns EnvioMensajesServiceWSBindingPortType
	 */
    @WebEndpoint(name = "EnvioMensajesServicePort")
    public EnvioMensajesServiceWSBindingPortType getEnvioMensajesServicePort() {
        return super.getPort(new QName("http://misim.redsara.es/misim-bus-webapp/", "EnvioMensajesServicePort"), EnvioMensajesServiceWSBindingPortType.class);
    }

    /**
	 * Gets the envio mensajes service port.
	 *
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default values.
	 * @return returns EnvioMensajesServiceWSBindingPortType
	 */
    @WebEndpoint(name = "EnvioMensajesServicePort")
    public EnvioMensajesServiceWSBindingPortType getEnvioMensajesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://misim.redsara.es/misim-bus-webapp/", "EnvioMensajesServicePort"), EnvioMensajesServiceWSBindingPortType.class, features);
    }

    /**
	 * Internal get wsdl location.
	 *
	 * @return the url
	 */
    private static URL internalGetWsdlLocation() {
        if (ENVIOMENSAJESSERVICE_EXCEPTION!= null) {
            throw ENVIOMENSAJESSERVICE_EXCEPTION;
        }
        return ENVIOMENSAJESSERVICE_WSDL_LOCATION;
    }

}
