
package es.gob.oaw.sim;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EnvioMensajesServiceWSBindingPortType", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnvioMensajesServiceWSBindingPortType {


    /**
     * 
     * @param peticion
     * @return
     *     returns Respuesta
     */
    @WebMethod(action = "enviarMensaje")
    @WebResult(name = "Respuesta", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/respuesta", partName = "respuesta")
    Respuesta enviarMensaje(
        @WebParam(name = "Peticion", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/peticion", partName = "peticion")
        Peticion peticion);

}
